sudo: false
language: java
notifications:
  email: false
  pushover:
    on_failure: always
    on_success: change
    api_key:
      secure: bX37kfotzuNAU9FVkZ8KZW+xhlz2g9iTs8phXWwNhz6CXCN/osl0jFKvycKOyo2WwJKPRcLmhN1bli3H7iinkS6k2X0daGUNuMKX/+IndqBHLeye+INoPJv0H6NusA+698bq6xNiLqSEKvZGPGPF1cEPk6XaL1ChF6894U9MbjL/gKqyAZAPQJG8XOs+EOs/M5ESmvX0QNxG6JxAqnDhlQ3+CbBM0fTJ4Wwmcbqtr9Q1ilAWx7Pd41CJnuw/ZAAZ7qTaMWSwHJ7fEIkhWhrp/ouzSJSV1OE13WW4GYn79OHjvNKKd2/ewrSXK/rKaygfRQ80nLkS73We1hy28AsTJvNrrxl6ZFDn579V5F+IsSDXMCCJ1kgMdQiRXuQbM0ARM2Cw2qNSzVLc3YmCwsrkRV53KYhEFWnhUUuPbSsPhmdF7M42t8ZsifJNVC+SQgRkBuwXp7h/5xOhRM3naXPIj+NaXepkS8fcnTeSgZcopmmb6l+F66sW8DNxyGZ8avg4ktQsCRT6QkA71w4SY87sF3PIzlpiLA+hD42FUWQdtcDJZ/U8eYkaM/jElib6qFmAN9CYUOqv13uXJFPdAjgtFABH56KQTwNZdMuPY4LZluPrvkxA+bcCjUhFXVFt2aPrqf49EQUrU1N8g1sn80NimD6sm7rjqrKvT8Tj/LzQ5nM=
    users:
      - secure: G96H1Sg8p/yMJ439tQ4yKv3NUUOa1lJkPALgyAyU7RBOufWVp7kZaSoyfZicxbvNEewlsr3T29Irt5lpBUVx0k1BO4S+anlHxtke8bAZp7pztBgpf8JBsg/zQDPc8YnNX6Oy71z92i04Ahp3wFBfiqFpH8TqcXAGZ+OulHfYHYhZLAJFe9AfKJ5E7aIYNlI0FjOxj7IVBIJ0jfgA0fd4n2AIG02BNLLj7sWv8CfzT3hISObYV/AbfIVCVsouqnNp2wdela8Oygult35oHmEhbBUIYXpa2vLQxv8WUZPR36kYxyUz0ev0b79zvdaC3n0AdVaL2sYDi8h+mesPBndeozbq06zzJfGxG9uCI5nX3BIcIP/5DUEu7S7pqqawbPFQJaDQbhHDMCMWARW7rb+uATJww/vXFRMjyRS8BPCuoyLA49zcn6xiTOJ7PL9bHJ2JICRjuOVOWb99MMT7PTbbt8DT16XBP5R4wK7ctSDr+yTWinRZ0pBlOEILMca2ysiM5fW3U/fU5aGM0cpI9JpPV7hAsm/ls50I3YJQ09aXlqb2re7dBDkx6r4fdXYYLXhr/lFI78N8zoLeI32Je6HCJ+C7HQJ1WruvKJDgyO/V4yEnb7DjU6ZnlJPGqosZ3BM1QPXrYNZjm5N+cxbzA8/M151Iy6a302zkkJfI4FBU03A=
addons:
  artifacts:
    branch: master
    bucket: ceylon.vasileff.com
    target_paths: modules
    paths:
      - ./modules
    key:
      secure: RUsmFiFDh60xeniW1hXejZ5FNfOMn9R7D2L7sWMoTJ+UU0xLD2sEK1iS2H2r8LrCmzLHfFPCVSbTXr3iwBfB7GDQLWCVG/mdfDDoQwg7pq2+Mwd1gpNCt3XEgO0rEvctVlq6yQgAgTNrzvVm6Hf08vSfnZNhBzLAJ8gYw14s/SrPmlwI8qJlr9/TGMo7vsdWZG0Pumja1Q7inFunMOq+raChr+Csu1XN8GKAglghv31GKv2kcAv21aLGyf70+HZ2pbMXlP0okrc5RrHaahy29Suqh10utlTRzbZpcFm5bJYPvWKlPD5B7DMf+5NwU3gEYovw1lb3qOEmrS8Yz03hX/chxSe2USFZPj0x3fOoKJeyjHZIFi/85Q1ELD3iGZd9cGvBVTnkElRgbgQcEt3/hOqkmmrmdL2Psv/7oN0+UlkXNk8VRcdjhddoax9mkIula+mSIbKLgSf/XYMvGzxAhcK4kjToJEMsgrecqyrUFUM+YqpyafHL51PmLub2bMtHdM5BruzCO4z2bQ36zH353Ba5nbR+uDprazK/xCPpfCEmsjhsXnk/dahNDwLWxvA3WLt8asndmE3a69VOQalQoRFAvZb9NgGkZG2uyT8UqQ4CyKvFqwGlKMVT6MkV53cYKGLQe3o4XSmsegK/j7yssKGWHJajinjMddX4inBJR8k=
    secret:
      secure: Vv4FTSnfc0X5840qY0WQeNi5qGBuLOgpTv+JaTDM6KLQBdtD1LLHedGteXzhMwJhRkjoTDmxi0ZS//CwHIz/IaEvuLmbeOx6xZyjL3YD8kPpuJw3prAEaRgDvrp9VmI6LrSebrQLEydDVvJauk+CI5fGhcBAj1gtdo+loze83gCffZuop4MmFW221UfZWsvYcybHpz87BYSbhPLLLi9GTTV9zo5J8r8bG0nJ/NC+RiDuBklFBmWau9NrhF/o8SwP9RCxsiUXOgx1ukUPQacGByD2OyRjqrA2AUXvNy/kU6VroDDX54xGR2uX+I6eSQCEfE7UmGMeVd6BsixQz6MqN/EfRzFXbxA5xt97tV7Vizdy9uad8DW07YYuJZHnElySpu7t6y6rHN4MgcGqHx6XynfhWaOzRwu9lyLIAH3Rgzz2n9QKhde9N7QBnBT5EPrgKcGXQdhVxHIKUarDQIvWQ8aXGXT39QKArfn9wY+zu+EaijyMJb6BhiglfM/Z8XBCOTgkisbctWO4h14kaC49QCm3uPUb0P7gHE1DKp3bmAKGfnbXc2R2mU/sQAwMJCbe5hZhcQ9afhXQqWE6wrFAo0OeHUBpJZ/CAc/VhW8n1qTasokHluqYyEWwl5Zw399mKX8z6LO5GcM+zrxpMmZFIRRj/6f+WqSly8tkgXQGcyc=
jdk:
  - oraclejdk8
install:
  - wget --quiet --output-document=/tmp/ceylon.zip $CEYLON
  - unzip -q /tmp/ceylon.zip
  - export PATH=$PATH:$PWD/ceylon-1.3.2/bin/
  - export CEYLON_HOME=$PWD/ceylon-1.3.2
  - echo -e '\n[repository "s3"]\nurl=http://ceylon.vasileff.com/modules\n[repositories]\nremote=+s3' >> $TRAVIS_BUILD_DIR/.ceylon/config
  - ceylon plugin install --force com.vasileff.ceylon.dart.cli/1.3.2-DP5-SNAPSHOT
  - ceylon install-dart --out +USER
before_script:
  - ceylon compile,compile-js,compile-dart
script:
    - ceylon test,test-js $TEST_MODULE
env:
  global:
    - CEYLON="http://ceylon-lang.org/download/dist/1_3_2"
    - TEST_MODULE="test.com.vasileff.ceylon.model"

